### ISSUE TITLE
No longer tracks instances after upgrade

### ISSUE THREAD

**Issue by LMarkham** [oathgg/InstanceBoostTracker#64]
Upgrade from: 0626494 to either 46148f0 or 9b58bc2 causes the app to no longer track instance information in the UI. 

Fixed by downgrading.

macOS - Stable (no beta)

**Comment by oathgg** [comment]
Hi @LMarkham, can you verify if the Lockout tracking feature is still enabled in settings?

**Comment by LMarkham** [comment]
It is enabled still.

**Comment by oathgg** [comment]
Latest release is: https://github.com/oathgg/InstanceBoostTracker/commit/96a6b95e6dfaf47c6188dcac70b995b841661c0a, everything works for me in that release. Are you using that version?

**Comment by oathgg** [comment]
Hi @LMarkham, did updating to the latest release solve the issue?

**Comment by LMarkham** [comment]
Sorry. No it doesn't. Still same issue. It fails to work with the 2 newer versions. Goin g back manually works great.

![IMG_0252](https://user-images.githubusercontent.com/47163788/88573356-38d3b080-d006-11ea-909f-ab7885758d75.jpeg)

**Comment by LMarkham** [comment]
Just for the sake of clarity, the image shows my run from yesterday, not today.

**Comment by oathgg** [comment]
@LMarkham, I've just reinstalled the current version of the addon on a fresh account, and it worked out of the box. Is it possible for you to hit me up on discord so we can have a look together?

**Comment by LMarkham** [comment]
Yup. My discord name is SaditicNerd#1865. I also have zoom we could use too if you want.

**Comment by LMarkham** [comment]
I updated to the news build today the on you just recently released and we are working again.
