### ISSUE TITLE
Time Taken (TT) only shows minutes

### ISSUE THREAD

**Issue by sge461** [oathgg/InstanceBoostTracker#67]
The solution I found for this problem is to change the line `if duration:gethours() > 1 then` to `if duration:gethours() > 0 then` in the [GUILockouts.lua line 60](https://github.com/oathgg/InstanceBoostTracker/blob/8d74ed912261aab0b0ce308559f0c6f43fe62ca1/UI/GUILockouts.lua#L60). Because if a run takes longer than an hour and less than two hours it will return 1. So to check if a run is over one hour it needs to be greater than zero.

![tempsnip](https://user-images.githubusercontent.com/13168332/90657509-f5561600-e242-11ea-88d4-1ebbd3ca8cff.png)

The result should look like intended:

![tempsnip2](https://user-images.githubusercontent.com/13168332/90659733-541c8f00-e245-11ea-9db1-a384f8be69d8.png)

**Comment by oathgg** [comment]
Nice catch, I didn't even realize there was a bug like that!

**Comment by oathgg** [comment]
Fixed in https://github.com/oathgg/InstanceBoostTracker/commit/31f53c8c2244562dbf6318d5cfdf613d7f5c00b1
